name: CalebCompass
version: 2.1
main: calebcompass.calebcompass.CalebCompass
api-version: 1.13
description: CalebCompass

commands:
  calebcompass:
    usage: '§e/calebcompass help'
    aliases: [calcomp]
