name: CalebCompass
version: 2.0
main: calebcompass.calebcompass.CalebCompass
api-version: 1.16
description: CalebCompass

commands:
  calebcompass:
    usage: '§e/calebcompass help'
    aliases: [calcomp]
